trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  node.version: '18.x'
  buildConfiguration: 'production'
  webAppName: 'augur-dashboard'
  azureSubscription: 'Azure-Subscription-Connection'
  resourceGroupName: 'augur-rg'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: BuildJob
    displayName: 'Build job'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(node.version)'
      displayName: 'Install Node.js'

    - script: |
        npm ci
      displayName: 'Install dependencies'

    - script: |
        npm run lint
      displayName: 'Run linting'

    - script: |
        npm run build
      displayName: 'Build application'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'out'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy built files to artifact staging directory'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish build artifacts'

- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Deploy job'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download build artifacts'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: '$(System.ArtifactsDirectory)/drop'
        api_location: ''
        output_location: ''
        azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
      displayName: 'Deploy to Azure Static Web App' 